[versions]
kotlin = "1.9.20"
kotlinCoroutines = "1.4.2"
shadow = "8.1.1"
paper = "1.21-R0.1-SNAPSHOT"
creative = "1.7.2"
sonatypeCentralPortalPublisher = "1.2.3"
solidMaterial = "1.21-1.1.0"

[libraries]
kotlinJvm = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

creativeApi = { module = "team.unnamed:creative-api", version.ref = "creative" }
creativeSerializer = { module = "team.unnamed:creative-serializer-minecraft", version.ref = "creative" }
solidMaterial = { module = "io.github.solid-resourcepack:solid-material-api", version.ref = "solidMaterial" }

[bundles]
creative = [
    "creativeApi",
    "creativeSerializer"
]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
sonatypeCentralPortalPublisher = { id = "net.thebugmc.gradle.sonatype-central-portal-publisher", version.ref = "sonatypeCentralPortalPublisher" }